apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: mysql:3306
    database: nyc_taxi
    user: ${MYSQL_APP_USER}
    secureJsonData:
      password: ${MYSQL_APP_PASSWORD}
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10